name: deploy-django

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          role-duration-seconds: 3600
          aws-region: ap-southeast-2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install EB CLI
        run: |
          pip install awsebcli --upgrade --user
          eb --version
      - name: Deploy
        run: eb deploy
      
    

